background:
  concentrations:
    co2:
      backgroundCo2File: ./backgroundCo2Concentrations/background_2018.nc
      rename: mix_background
      stationWithoutBackgroundConcentration: DAILYMEAN
      userProvidedBackgroundConcentration: 410
congrad:
  communication_file: ./tmp/LumiaGUI-2024-02-27T01_02/LumiaGUI-2024-02-27T01_02-congrad.nc
  executable: ${lumiacode.homedir}/src/congrad/congrad.exe
  gradient_norm_reduction: 1.e12
  max_number_of_iterations: 128
correlation:
  inputdir: ./data/corr
emissions:
  '*':
    archive: rclone:lumia:fluxes/nc/
    error_structure: linear
    path: /data/fluxes/nc
  co2:
    categories:
      biosphere:
        error_min: 0
        is_ocean: false
        origin: VPRM
        tcorr: ${optimize.emissions.co2.biosphere.temporal_correlation}
        unit: PgC
      fossil:
        error_min: 0
        is_ocean: false
        optimize: false
        origin: EDGARv4_LATEST
        tcorr: ${optimize.emissions.co2.fossil.temporal_correlation}
        unit: PgC
      ocean:
        error_min: 0
        is_ocean: true
        optimize: false
        origin: mikaloff01
        tcorr: ${optimize.emissions.co2.ocean.temporal_correlation}
        unit: PgC
    interval: ${run.time.timestep}
    location:
      biosphere: CARBONPORTAL
      fossil: CARBONPORTAL
      ocean: LOCAL
    path: ${run.paths.data}/fluxes/nc/
    prefix: flux_co2.
    region: ${run.grid}
    regionName: ${run.gridname}
  region: ${run.grid}
  regionName: ${run.gridname}
emissions.*.error_structure: linear
lumiacode:
  homedir: /home/arndt/nateko/dev/lumia/lumiaDA/lumia
model:
  exec: ${lumiacode.homedir}/transport/multitracer.py
  options:
    serial: false
  output:
    steps:
    - apri
    - apos
  path:
    footprints: ${run.paths.footprints}
    output: ${run.paths.output}
    temp: ${run.paths.temp}
  transport:
    exec:
      exec: /lumia/transport/multitracer.py
    serial: false
observations:
  co2:
    file:
      dicoveredObsData: ./output/LumiaGUI-2024-05-14T15_22/LumiaGUI-2024-05-14T15_22-DiscoveredObservations-co2.csv #./output/LumiaGUI-2024-02-27T01_02/LumiaGUI-2024-02-26T10_30-DiscoveredObservations.csv
      discoverData: false
      location: CARBONPORTAL
      path: observations.tar.gz
      ranking:
      - ObsPack
      - Level2
      - Level1
      - NRT
      - AnyOther
      rename: background:mix_background
      selectedObsData: ./output/LumiaGUI-2024-05-14T15_22/LumiaGUI-2024-05-14T15_22-selected-ObsData-co2.csv
      selectedPIDs: ./output/LumiaGUI-2024-05-14T15_22/LumiaGUI-2024-05-14T15_22-selected-PIDs-co2.csv
      tracer: co2
    units: ppm
  end: ${run.time.end}
  file:
    co2:
      discoverData: true
      selectedObsData: None
      selectedPIDs: None
  filters:
    CountriesExcluded: []
    ICOSonly: false
    StationsExcluded: []
    bSamplingHeight: false
    bStationAltitude: false
    inletMaxHeight: 800
    inletMinHeight: 20
    stationMaxAlt: 6500
    stationMinAlt: 30
  start: ${run.time.start}
  uncertainty:
    background: 1.822
    default_weekly_error: 1.5
    dyn:
      freq: 7D
    frequency: dyn
    model: 1.5
    obs_field: err
    setup: false
    systematicErrEstim: 0.5
  validation_file: false
optimize:
  emissions:
    co2:
      biosphere:
        adjust: true
        annual_uncertainty: 0.47 PgC
        npoints: 2500
        optimization_interval: 7d
        spatial_correlation: 500-g
        temporal_correlation: 30D
      fossil:
        adjust: false
      ocean:
        adjust: false
      resample: false
  observations:
    co2:
      uncertainty:
        type: weekly
path:
  data: /data
region: ${run.region}
run:
  grid: ${Grid:{lon0:-15.000,lat0:33.000,lon1:35.000,lat1:73.000,dlon:0.25000, dlat:0.25000}}
  gridname: eurocom025x025
  paths:
    data: .
    footprints: /home/arndt/nateko/data/icos/DICE/footprints
    output: ./output
    temp: ./tmp
  region:
    dlat: 0.25
    dlon: 0.25
    lat0: 33.0
    lat1: 73.0
    lon0: -15.0
    lon1: 35.0
  thisRun:
    PythonVersion: Python environment version is Python 3.10.10
    hostName: tux.nateko.lu.se
    platformCore: Linux-5.15.0-97-generic-x86_64-with-glibc2.35
    platformFlavour: 07-Ubuntu SMP Wed Feb 7 13:26:48 UTC 202
    uniqueIdentifierDateTime: 2024-02-27T01_02
    uniqueOutputPrefix: ./output/LumiaGUI-2024-02-27T01_02/LumiaGUI-2024-02-27T01_02-
    uniqueTmpPrefix: ./tmp/LumiaGUI-2024-02-27T01_02/LumiaGUI-2024-02-27T01_02-
    username: cec-ami
  time:
    end: '2018-02-01 23:59:59'
    start: '2018-01-01 00:00:00'
    timestep: 1h
  tracers:
  - co2
softwareUsed:
  lumia:
    branch: gitkraken://repolink/778bf0763fae9fad55be85dde4b42613835a3528/branch/LumiaDA?url=git%40github.com%3Alumia-dev%2Flumia.git
    commit: gitkraken://repolink/778bf0763fae9fad55be85dde4b42613835a3528/commit/5e5e9777a227631d6ceeba4fd8cff9b241c55de1?url=git%40github.com%3Alumia-dev%2Flumia.git
    git:
      branch: LumiaGUI
      commit: 0879c961b148ae7ed45127560b19d56656689f74
      location: git@github.com:lumia-dev/lumia/commit/0879c961b148ae7ed45127560b19d56656689f74
      url: git@github.com:lumia-dev/lumia.git
  runflex:
    branch: gitkraken://repolink/b9411fbf7aeeb54d7bb34331a98e2cc0b6db9d5f/branch/v2?url=https%3A%2F%2Fgithub.com%2Flumia-dev%2Frunflex.git
    commit: gitkraken://repolink/b9411fbf7aeeb54d7bb34331a98e2cc0b6db9d5f/commit/aad612b36a247046120bda30c8837acb5dec4f26?url=https%3A%2F%2Fgithub.com%2Flumia-dev%2Frunflex.git
    git:
      branch: v2
      commit: aad612b36a247046120bda30c8837acb5dec4f26
      location: git@github.com:lumia-dev/runflex/commit/aad612b36a247046120bda30c8837acb5dec4f26
      url: git@github.com:lumia-dev/runflex.git
tag: ''
thisConfigFile:
  dataformat:
    subversion: 2
    version: 6
transport:
  output: T
  steps: forward
var4d:
  communication:
    file: ./tmp/LumiaGUI-2024-02-27T01_02/LumiaGUI-2024-02-27T01_02-congrad.nc
  max_iter: 333
